/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-37-g833d66d-dirty

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x0000012D,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'I', 'n', 'k', 'l', 'i', 'n', 'e', 0},
    .x1009_manufacturerHardwareVersion = {'2', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'2', '.', '0', '0', 0},
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x0000010C,
        .productCode = 0x00000001,
        .revisionNumber = 0x00000014,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000300,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x00000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x00000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1003_pre_definedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x100C_guardTime = 0x0000,
    .x100D_lifeTimeFactor = 0x00,
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x1F80_NMTStartup = 0x00000004,
    .x2000_actualValues_sub0 = 0x03,
    .x2000_actualValues = {0, 0, 0},
    .x2010_alarmStateRegister_sub0 = 0x02,
    .x2010_alarmStateRegister = {0x07, 0xFF},
    .x2011_operatingStateRegister_sub0 = 0x03,
    .x2011_operatingStateRegister = {0x3F, 0x02, 0x03},
    .x2012_configurationStateRegister_sub0 = 0x03,
    .x2012_configurationStateRegister = {0x0F, 0x92, 0x07},
    .x2013_vendorStateRegister_sub0 = 0x10,
    .x2013_vendorStateRegister = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x2020_deviceStateRegister = 0x00,
    .x205B_maintananceStateRegister_sub0 = 0x01,
    .x205B_maintananceStateRegister = {0x07},
    .x2100_minimumValueOf2500H_sub0 = 0x03,
    .x2100_minimumValueOf2500H = {4, 5, 0},
    .x2110_maximumValueOf2500H_sub0 = 0x03,
    .x2110_maximumValueOf2500H = {40, 50, 0},
    .x2120_stepWidthOf2500H_sub0 = 0x03,
    .x2120_stepWidthOf2500H = {1, 1, 1},
    .x2500_setppoints_sub0 = 0x03,
    .x2500_setppoints = {20, 10, 0},
    .x2511_operatingControlRegister_sub0 = 0x03,
    .x2511_operatingControlRegister = {0x2F, 0x04, 0x03},
    .x2520_deviceControlRegister = 0x01,
    .x2600_minimumLimitsOf2000H_sub0 = 0x03,
    .x2600_minimumLimitsOf2000H = {0, 0, -1000},
    .x2610_maximumLimitsOf2000H_sub0 = 0x03,
    .x2610_maximumLimitsOf2000H = {200, 100, 1000},
    .x2621_configurationParameter_sub0 = 0x07,
    .x2621_configurationParameter = {0, 318, 32, 32, 0, 10, 0},
    .x2670_runLogData_sub0 = 0x05,
    .x2670_runLogData = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x3030_numberOfServiceErrorStrings = 0x0080,
    .x3031_serviceErrorStringLanguageSupport_sub0 = 0x05,
    .x3031_serviceErrorStringLanguageSupport = {0x01, 0x01, 0x01, 0x01, 0x01},
    .x3032_setServiceErrorLanguage = 0x0001,
    .x4000_serviceErrorString0 = {'0', 0},
    .x4001_serviceErrorString1 = {'0', 0},
    .x4002_serviceErrorString2 = {'0', 0},
    .x4003_serviceErrorString3 = {'0', 0},
    .x4004_serviceErrorString4 = {'0', 0},
    .x4005_serviceErrorString5 = {'0', 0},
    .x4006_serviceErrorString6 = {'0', 0},
    .x4007_serviceErrorString7 = {'0', 0},
    .x4008_serviceErrorString8 = {'0', 0},
    .x4009_serviceErrorString9 = {'0', 0},
    .x400A_serviceErrorString10 = {'0', 0},
    .x400B_serviceErrorString11 = {'0', 0},
    .x400C_serviceErrorString12 = {'0', 0},
    .x400D_serviceErrorString13 = {'0', 0},
    .x400E_serviceErrorString14 = {'0', 0},
    .x400F_serviceErrorString15 = {'0', 0},
    .x4010_serviceErrorString16 = {'0', 0},
    .x4011_serviceErrorString17 = {'0', 0},
    .x4012_serviceErrorString18 = {'0', 0},
    .x4013_serviceErrorString19 = {'0', 0},
    .x4014_serviceErrorString20 = {'0', 0},
    .x4015_serviceErrorString21 = {'0', 0},
    .x4016_serviceErrorString22 = {'0', 0},
    .x4017_serviceErrorString23 = {'0', 0},
    .x4018_serviceErrorString24 = {'0', 0},
    .x4019_serviceErrorString25 = {'0', 0},
    .x401A_serviceErrorString26 = {'0', 0},
    .x401B_serviceErrorString27 = {'0', 0},
    .x401C_serviceErrorString28 = {'0', 0},
    .x401D_serviceErrorString29 = {'0', 0},
    .x401E_serviceErrorString30 = {'0', 0},
    .x401F_serviceErrorString31 = {'0', 0},
    .x4020_serviceErrorString32 = {'0', 0},
    .x4021_serviceErrorString33 = {'0', 0},
    .x4022_serviceErrorString34 = {'0', 0},
    .x4023_serviceErrorString35 = {'0', 0},
    .x4024_serviceErrorString36 = {'0', 0},
    .x4025_serviceErrorString37 = {'0', 0},
    .x4026_serviceErrorString38 = {'0', 0},
    .x4027_serviceErrorString39 = {'0', 0},
    .x4028_serviceErrorString40 = {'0', 0},
    .x4029_serviceErrorString41 = {'0', 0},
    .x402A_serviceErrorString42 = {'0', 0},
    .x402B_serviceErrorString43 = {'0', 0},
    .x402C_serviceErrorString44 = {'0', 0},
    .x402D_serviceErrorString45 = {'0', 0},
    .x402E_serviceErrorString46 = {'0', 0},
    .x402F_serviceErrorString47 = {'0', 0},
    .x4030_serviceErrorString48 = {'0', 0},
    .x4031_serviceErrorString49 = {'0', 0},
    .x4032_serviceErrorString50 = {'0', 0},
    .x4033_serviceErrorString51 = {'0', 0},
    .x4034_serviceErrorString52 = {'0', 0},
    .x4035_serviceErrorString53 = {'0', 0},
    .x4036_serviceErrorString54 = {'0', 0},
    .x4037_serviceErrorString55 = {'0', 0},
    .x4038_serviceErrorString56 = {'0', 0},
    .x4039_serviceErrorString57 = {'0', 0},
    .x403A_serviceErrorString58 = {'0', 0},
    .x403B_serviceErrorString59 = {'0', 0},
    .x403C_serviceErrorString60 = {'0', 0},
    .x403D_serviceErrorString61 = {'0', 0},
    .x403E_serviceErrorString62 = {'0', 0},
    .x403F_serviceErrorString63 = {'0', 0},
    .x4040_serviceErrorString64 = {'0', 0},
    .x4041_serviceErrorString65 = {'0', 0},
    .x4042_serviceErrorString66 = {'0', 0},
    .x4043_serviceErrorString67 = {'0', 0},
    .x4044_serviceErrorString68 = {'0', 0},
    .x4045_serviceErrorString69 = {'0', 0},
    .x4046_serviceErrorString70 = {'0', 0},
    .x4047_serviceErrorString71 = {'0', 0},
    .x4048_serviceErrorString72 = {'0', 0},
    .x4049_serviceErrorString73 = {'0', 0},
    .x404A_serviceErrorString74 = {'0', 0},
    .x404B_serviceErrorString75 = {'0', 0},
    .x404C_serviceErrorString76 = {'0', 0},
    .x404D_serviceErrorString77 = {'0', 0},
    .x404E_serviceErrorString78 = {'0', 0},
    .x404F_serviceErrorString79 = {'0', 0},
    .x4050_serviceErrorString80 = {'0', 0},
    .x4051_serviceErrorString81 = {'0', 0},
    .x4052_serviceErrorString82 = {'0', 0},
    .x4053_serviceErrorString83 = {'0', 0},
    .x4054_serviceErrorString84 = {'0', 0},
    .x4055_serviceErrorString85 = {'0', 0},
    .x4056_serviceErrorString86 = {'0', 0},
    .x4057_serviceErrorString87 = {'0', 0},
    .x4058_serviceErrorString88 = {'0', 0},
    .x4059_serviceErrorString89 = {'0', 0},
    .x405A_serviceErrorString90 = {'0', 0},
    .x405B_serviceErrorString91 = {'0', 0},
    .x405C_serviceErrorString92 = {'0', 0},
    .x405D_serviceErrorString93 = {'0', 0},
    .x405E_serviceErrorString94 = {'0', 0},
    .x405F_serviceErrorString95 = {'0', 0},
    .x4060_serviceErrorString96 = {'0', 0},
    .x4061_serviceErrorString97 = {'0', 0},
    .x4062_serviceErrorString98 = {'0', 0},
    .x4063_serviceErrorString99 = {'0', 0},
    .x4064_serviceErrorString100 = {'0', 0},
    .x4065_serviceErrorString101 = {'0', 0},
    .x4066_serviceErrorString102 = {'0', 0},
    .x4067_serviceErrorString103 = {'0', 0},
    .x4068_serviceErrorString104 = {'0', 0},
    .x4069_serviceErrorString105 = {'0', 0},
    .x406A_serviceErrorString106 = {'0', 0},
    .x406B_serviceErrorString107 = {'0', 0},
    .x406C_serviceErrorString108 = {'0', 0},
    .x406D_serviceErrorString109 = {'0', 0},
    .x406E_serviceErrorString110 = {'0', 0},
    .x406F_serviceErrorString111 = {'0', 0},
    .x4070_serviceErrorString112 = {'0', 0},
    .x4071_serviceErrorString113 = {'0', 0},
    .x4072_serviceErrorString114 = {'0', 0},
    .x4073_serviceErrorString115 = {'0', 0},
    .x4074_serviceErrorString116 = {'0', 0},
    .x4075_serviceErrorString117 = {'0', 0},
    .x4076_serviceErrorString118 = {'0', 0},
    .x4077_serviceErrorString119 = {'0', 0},
    .x4078_serviceErrorString120 = {'0', 0},
    .x4079_serviceErrorString121 = {'0', 0},
    .x407A_serviceErrorString122 = {'0', 0},
    .x407B_serviceErrorString123 = {'0', 0},
    .x407C_serviceErrorString124 = {'0', 0},
    .x407D_serviceErrorString125 = {'0', 0},
    .x407E_serviceErrorString126 = {'0', 0},
    .x407F_serviceErrorString127 = {'0', 0},
    .x6000_digitalInputs1_sub0 = 0x06,
    .x6000_digitalInputs1 = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6200_digitalInputs2_sub0 = 0x03,
    .x6200_digitalInputs2 = {0x00, 0x00, 0x00},
    .x6401_analogInputs_sub0 = 0x06,
    .x6401_analogInputs = {0, 0, 0, 0, 0, 0}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_100C_guardTime;
    OD_obj_var_t o_100D_lifeTimeFactor;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_var_t o_1F80_NMTStartup;
    OD_obj_array_t o_2000_actualValues;
    OD_obj_array_t o_2010_alarmStateRegister;
    OD_obj_array_t o_2011_operatingStateRegister;
    OD_obj_array_t o_2012_configurationStateRegister;
    OD_obj_array_t o_2013_vendorStateRegister;
    OD_obj_var_t o_2020_deviceStateRegister;
    OD_obj_array_t o_205B_maintananceStateRegister;
    OD_obj_array_t o_2100_minimumValueOf2500H;
    OD_obj_array_t o_2110_maximumValueOf2500H;
    OD_obj_array_t o_2120_stepWidthOf2500H;
    OD_obj_array_t o_2500_setppoints;
    OD_obj_array_t o_2511_operatingControlRegister;
    OD_obj_var_t o_2520_deviceControlRegister;
    OD_obj_array_t o_2600_minimumLimitsOf2000H;
    OD_obj_array_t o_2610_maximumLimitsOf2000H;
    OD_obj_array_t o_2621_configurationParameter;
    OD_obj_var_t o_2622_presetOperatingCtrl;
    OD_obj_array_t o_2670_runLogData;
    OD_obj_var_t o_3030_numberOfServiceErrorStrings;
    OD_obj_array_t o_3031_serviceErrorStringLanguageSupport;
    OD_obj_var_t o_3032_setServiceErrorLanguage;
    OD_obj_var_t o_4000_serviceErrorString0;
    OD_obj_var_t o_4001_serviceErrorString1;
    OD_obj_var_t o_4002_serviceErrorString2;
    OD_obj_var_t o_4003_serviceErrorString3;
    OD_obj_var_t o_4004_serviceErrorString4;
    OD_obj_var_t o_4005_serviceErrorString5;
    OD_obj_var_t o_4006_serviceErrorString6;
    OD_obj_var_t o_4007_serviceErrorString7;
    OD_obj_var_t o_4008_serviceErrorString8;
    OD_obj_var_t o_4009_serviceErrorString9;
    OD_obj_var_t o_400A_serviceErrorString10;
    OD_obj_var_t o_400B_serviceErrorString11;
    OD_obj_var_t o_400C_serviceErrorString12;
    OD_obj_var_t o_400D_serviceErrorString13;
    OD_obj_var_t o_400E_serviceErrorString14;
    OD_obj_var_t o_400F_serviceErrorString15;
    OD_obj_var_t o_4010_serviceErrorString16;
    OD_obj_var_t o_4011_serviceErrorString17;
    OD_obj_var_t o_4012_serviceErrorString18;
    OD_obj_var_t o_4013_serviceErrorString19;
    OD_obj_var_t o_4014_serviceErrorString20;
    OD_obj_var_t o_4015_serviceErrorString21;
    OD_obj_var_t o_4016_serviceErrorString22;
    OD_obj_var_t o_4017_serviceErrorString23;
    OD_obj_var_t o_4018_serviceErrorString24;
    OD_obj_var_t o_4019_serviceErrorString25;
    OD_obj_var_t o_401A_serviceErrorString26;
    OD_obj_var_t o_401B_serviceErrorString27;
    OD_obj_var_t o_401C_serviceErrorString28;
    OD_obj_var_t o_401D_serviceErrorString29;
    OD_obj_var_t o_401E_serviceErrorString30;
    OD_obj_var_t o_401F_serviceErrorString31;
    OD_obj_var_t o_4020_serviceErrorString32;
    OD_obj_var_t o_4021_serviceErrorString33;
    OD_obj_var_t o_4022_serviceErrorString34;
    OD_obj_var_t o_4023_serviceErrorString35;
    OD_obj_var_t o_4024_serviceErrorString36;
    OD_obj_var_t o_4025_serviceErrorString37;
    OD_obj_var_t o_4026_serviceErrorString38;
    OD_obj_var_t o_4027_serviceErrorString39;
    OD_obj_var_t o_4028_serviceErrorString40;
    OD_obj_var_t o_4029_serviceErrorString41;
    OD_obj_var_t o_402A_serviceErrorString42;
    OD_obj_var_t o_402B_serviceErrorString43;
    OD_obj_var_t o_402C_serviceErrorString44;
    OD_obj_var_t o_402D_serviceErrorString45;
    OD_obj_var_t o_402E_serviceErrorString46;
    OD_obj_var_t o_402F_serviceErrorString47;
    OD_obj_var_t o_4030_serviceErrorString48;
    OD_obj_var_t o_4031_serviceErrorString49;
    OD_obj_var_t o_4032_serviceErrorString50;
    OD_obj_var_t o_4033_serviceErrorString51;
    OD_obj_var_t o_4034_serviceErrorString52;
    OD_obj_var_t o_4035_serviceErrorString53;
    OD_obj_var_t o_4036_serviceErrorString54;
    OD_obj_var_t o_4037_serviceErrorString55;
    OD_obj_var_t o_4038_serviceErrorString56;
    OD_obj_var_t o_4039_serviceErrorString57;
    OD_obj_var_t o_403A_serviceErrorString58;
    OD_obj_var_t o_403B_serviceErrorString59;
    OD_obj_var_t o_403C_serviceErrorString60;
    OD_obj_var_t o_403D_serviceErrorString61;
    OD_obj_var_t o_403E_serviceErrorString62;
    OD_obj_var_t o_403F_serviceErrorString63;
    OD_obj_var_t o_4040_serviceErrorString64;
    OD_obj_var_t o_4041_serviceErrorString65;
    OD_obj_var_t o_4042_serviceErrorString66;
    OD_obj_var_t o_4043_serviceErrorString67;
    OD_obj_var_t o_4044_serviceErrorString68;
    OD_obj_var_t o_4045_serviceErrorString69;
    OD_obj_var_t o_4046_serviceErrorString70;
    OD_obj_var_t o_4047_serviceErrorString71;
    OD_obj_var_t o_4048_serviceErrorString72;
    OD_obj_var_t o_4049_serviceErrorString73;
    OD_obj_var_t o_404A_serviceErrorString74;
    OD_obj_var_t o_404B_serviceErrorString75;
    OD_obj_var_t o_404C_serviceErrorString76;
    OD_obj_var_t o_404D_serviceErrorString77;
    OD_obj_var_t o_404E_serviceErrorString78;
    OD_obj_var_t o_404F_serviceErrorString79;
    OD_obj_var_t o_4050_serviceErrorString80;
    OD_obj_var_t o_4051_serviceErrorString81;
    OD_obj_var_t o_4052_serviceErrorString82;
    OD_obj_var_t o_4053_serviceErrorString83;
    OD_obj_var_t o_4054_serviceErrorString84;
    OD_obj_var_t o_4055_serviceErrorString85;
    OD_obj_var_t o_4056_serviceErrorString86;
    OD_obj_var_t o_4057_serviceErrorString87;
    OD_obj_var_t o_4058_serviceErrorString88;
    OD_obj_var_t o_4059_serviceErrorString89;
    OD_obj_var_t o_405A_serviceErrorString90;
    OD_obj_var_t o_405B_serviceErrorString91;
    OD_obj_var_t o_405C_serviceErrorString92;
    OD_obj_var_t o_405D_serviceErrorString93;
    OD_obj_var_t o_405E_serviceErrorString94;
    OD_obj_var_t o_405F_serviceErrorString95;
    OD_obj_var_t o_4060_serviceErrorString96;
    OD_obj_var_t o_4061_serviceErrorString97;
    OD_obj_var_t o_4062_serviceErrorString98;
    OD_obj_var_t o_4063_serviceErrorString99;
    OD_obj_var_t o_4064_serviceErrorString100;
    OD_obj_var_t o_4065_serviceErrorString101;
    OD_obj_var_t o_4066_serviceErrorString102;
    OD_obj_var_t o_4067_serviceErrorString103;
    OD_obj_var_t o_4068_serviceErrorString104;
    OD_obj_var_t o_4069_serviceErrorString105;
    OD_obj_var_t o_406A_serviceErrorString106;
    OD_obj_var_t o_406B_serviceErrorString107;
    OD_obj_var_t o_406C_serviceErrorString108;
    OD_obj_var_t o_406D_serviceErrorString109;
    OD_obj_var_t o_406E_serviceErrorString110;
    OD_obj_var_t o_406F_serviceErrorString111;
    OD_obj_var_t o_4070_serviceErrorString112;
    OD_obj_var_t o_4071_serviceErrorString113;
    OD_obj_var_t o_4072_serviceErrorString114;
    OD_obj_var_t o_4073_serviceErrorString115;
    OD_obj_var_t o_4074_serviceErrorString116;
    OD_obj_var_t o_4075_serviceErrorString117;
    OD_obj_var_t o_4076_serviceErrorString118;
    OD_obj_var_t o_4077_serviceErrorString119;
    OD_obj_var_t o_4078_serviceErrorString120;
    OD_obj_var_t o_4079_serviceErrorString121;
    OD_obj_var_t o_407A_serviceErrorString122;
    OD_obj_var_t o_407B_serviceErrorString123;
    OD_obj_var_t o_407C_serviceErrorString124;
    OD_obj_var_t o_407D_serviceErrorString125;
    OD_obj_var_t o_407E_serviceErrorString126;
    OD_obj_var_t o_407F_serviceErrorString127;
    OD_obj_array_t o_6000_digitalInputs1;
    OD_obj_array_t o_6200_digitalInputs2;
    OD_obj_array_t o_6401_analogInputs;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = &OD_RAM.x1003_pre_definedErrorField[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 7
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 3
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 4
    },
    .o_100C_guardTime = {
        .dataOrig = &OD_RAM.x100C_guardTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_100D_lifeTimeFactor = {
        .dataOrig = &OD_RAM.x100D_lifeTimeFactor,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1F80_NMTStartup = {
        .dataOrig = &OD_RAM.x1F80_NMTStartup,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2000_actualValues = {
        .dataOrig0 = &OD_RAM.x2000_actualValues_sub0,
        .dataOrig = &OD_RAM.x2000_actualValues[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2010_alarmStateRegister = {
        .dataOrig0 = &OD_RAM.x2010_alarmStateRegister_sub0,
        .dataOrig = &OD_RAM.x2010_alarmStateRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2011_operatingStateRegister = {
        .dataOrig0 = &OD_RAM.x2011_operatingStateRegister_sub0,
        .dataOrig = &OD_RAM.x2011_operatingStateRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2012_configurationStateRegister = {
        .dataOrig0 = &OD_RAM.x2012_configurationStateRegister_sub0,
        .dataOrig = &OD_RAM.x2012_configurationStateRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2013_vendorStateRegister = {
        .dataOrig0 = &OD_RAM.x2013_vendorStateRegister_sub0,
        .dataOrig = &OD_RAM.x2013_vendorStateRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2020_deviceStateRegister = {
        .dataOrig = &OD_RAM.x2020_deviceStateRegister,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataLength = 1
    },
    .o_205B_maintananceStateRegister = {
        .dataOrig0 = &OD_RAM.x205B_maintananceStateRegister_sub0,
        .dataOrig = &OD_RAM.x205B_maintananceStateRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2100_minimumValueOf2500H = {
        .dataOrig0 = &OD_RAM.x2100_minimumValueOf2500H_sub0,
        .dataOrig = &OD_RAM.x2100_minimumValueOf2500H[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2110_maximumValueOf2500H = {
        .dataOrig0 = &OD_RAM.x2110_maximumValueOf2500H_sub0,
        .dataOrig = &OD_RAM.x2110_maximumValueOf2500H[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2120_stepWidthOf2500H = {
        .dataOrig0 = &OD_RAM.x2120_stepWidthOf2500H_sub0,
        .dataOrig = &OD_RAM.x2120_stepWidthOf2500H[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2500_setppoints = {
        .dataOrig0 = &OD_RAM.x2500_setppoints_sub0,
        .dataOrig = &OD_RAM.x2500_setppoints[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2511_operatingControlRegister = {
        .dataOrig0 = &OD_RAM.x2511_operatingControlRegister_sub0,
        .dataOrig = &OD_RAM.x2511_operatingControlRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2520_deviceControlRegister = {
        .dataOrig = &OD_RAM.x2520_deviceControlRegister,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_2600_minimumLimitsOf2000H = {
        .dataOrig0 = &OD_RAM.x2600_minimumLimitsOf2000H_sub0,
        .dataOrig = &OD_RAM.x2600_minimumLimitsOf2000H[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2610_maximumLimitsOf2000H = {
        .dataOrig0 = &OD_RAM.x2610_maximumLimitsOf2000H_sub0,
        .dataOrig = &OD_RAM.x2610_maximumLimitsOf2000H[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2621_configurationParameter = {
        .dataOrig0 = &OD_RAM.x2621_configurationParameter_sub0,
        .dataOrig = &OD_RAM.x2621_configurationParameter[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2622_presetOperatingCtrl = {
        .dataOrig = &OD_RAM.x2622_presetOperatingCtrl,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2670_runLogData = {
        .dataOrig0 = &OD_RAM.x2670_runLogData_sub0,
        .dataOrig = &OD_RAM.x2670_runLogData[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_3030_numberOfServiceErrorStrings = {
        .dataOrig = &OD_RAM.x3030_numberOfServiceErrorStrings,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_3031_serviceErrorStringLanguageSupport = {
        .dataOrig0 = &OD_RAM.x3031_serviceErrorStringLanguageSupport_sub0,
        .dataOrig = &OD_RAM.x3031_serviceErrorStringLanguageSupport[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_3032_setServiceErrorLanguage = {
        .dataOrig = &OD_RAM.x3032_setServiceErrorLanguage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_4000_serviceErrorString0 = {
        .dataOrig = &OD_RAM.x4000_serviceErrorString0[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4001_serviceErrorString1 = {
        .dataOrig = &OD_RAM.x4001_serviceErrorString1[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4002_serviceErrorString2 = {
        .dataOrig = &OD_RAM.x4002_serviceErrorString2[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4003_serviceErrorString3 = {
        .dataOrig = &OD_RAM.x4003_serviceErrorString3[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4004_serviceErrorString4 = {
        .dataOrig = &OD_RAM.x4004_serviceErrorString4[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4005_serviceErrorString5 = {
        .dataOrig = &OD_RAM.x4005_serviceErrorString5[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4006_serviceErrorString6 = {
        .dataOrig = &OD_RAM.x4006_serviceErrorString6[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4007_serviceErrorString7 = {
        .dataOrig = &OD_RAM.x4007_serviceErrorString7[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4008_serviceErrorString8 = {
        .dataOrig = &OD_RAM.x4008_serviceErrorString8[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4009_serviceErrorString9 = {
        .dataOrig = &OD_RAM.x4009_serviceErrorString9[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400A_serviceErrorString10 = {
        .dataOrig = &OD_RAM.x400A_serviceErrorString10[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400B_serviceErrorString11 = {
        .dataOrig = &OD_RAM.x400B_serviceErrorString11[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400C_serviceErrorString12 = {
        .dataOrig = &OD_RAM.x400C_serviceErrorString12[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400D_serviceErrorString13 = {
        .dataOrig = &OD_RAM.x400D_serviceErrorString13[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400E_serviceErrorString14 = {
        .dataOrig = &OD_RAM.x400E_serviceErrorString14[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_400F_serviceErrorString15 = {
        .dataOrig = &OD_RAM.x400F_serviceErrorString15[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4010_serviceErrorString16 = {
        .dataOrig = &OD_RAM.x4010_serviceErrorString16[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4011_serviceErrorString17 = {
        .dataOrig = &OD_RAM.x4011_serviceErrorString17[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4012_serviceErrorString18 = {
        .dataOrig = &OD_RAM.x4012_serviceErrorString18[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4013_serviceErrorString19 = {
        .dataOrig = &OD_RAM.x4013_serviceErrorString19[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4014_serviceErrorString20 = {
        .dataOrig = &OD_RAM.x4014_serviceErrorString20[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4015_serviceErrorString21 = {
        .dataOrig = &OD_RAM.x4015_serviceErrorString21[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4016_serviceErrorString22 = {
        .dataOrig = &OD_RAM.x4016_serviceErrorString22[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4017_serviceErrorString23 = {
        .dataOrig = &OD_RAM.x4017_serviceErrorString23[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4018_serviceErrorString24 = {
        .dataOrig = &OD_RAM.x4018_serviceErrorString24[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4019_serviceErrorString25 = {
        .dataOrig = &OD_RAM.x4019_serviceErrorString25[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401A_serviceErrorString26 = {
        .dataOrig = &OD_RAM.x401A_serviceErrorString26[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401B_serviceErrorString27 = {
        .dataOrig = &OD_RAM.x401B_serviceErrorString27[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401C_serviceErrorString28 = {
        .dataOrig = &OD_RAM.x401C_serviceErrorString28[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401D_serviceErrorString29 = {
        .dataOrig = &OD_RAM.x401D_serviceErrorString29[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401E_serviceErrorString30 = {
        .dataOrig = &OD_RAM.x401E_serviceErrorString30[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_401F_serviceErrorString31 = {
        .dataOrig = &OD_RAM.x401F_serviceErrorString31[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4020_serviceErrorString32 = {
        .dataOrig = &OD_RAM.x4020_serviceErrorString32[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4021_serviceErrorString33 = {
        .dataOrig = &OD_RAM.x4021_serviceErrorString33[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4022_serviceErrorString34 = {
        .dataOrig = &OD_RAM.x4022_serviceErrorString34[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4023_serviceErrorString35 = {
        .dataOrig = &OD_RAM.x4023_serviceErrorString35[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4024_serviceErrorString36 = {
        .dataOrig = &OD_RAM.x4024_serviceErrorString36[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4025_serviceErrorString37 = {
        .dataOrig = &OD_RAM.x4025_serviceErrorString37[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4026_serviceErrorString38 = {
        .dataOrig = &OD_RAM.x4026_serviceErrorString38[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4027_serviceErrorString39 = {
        .dataOrig = &OD_RAM.x4027_serviceErrorString39[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4028_serviceErrorString40 = {
        .dataOrig = &OD_RAM.x4028_serviceErrorString40[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4029_serviceErrorString41 = {
        .dataOrig = &OD_RAM.x4029_serviceErrorString41[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402A_serviceErrorString42 = {
        .dataOrig = &OD_RAM.x402A_serviceErrorString42[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402B_serviceErrorString43 = {
        .dataOrig = &OD_RAM.x402B_serviceErrorString43[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402C_serviceErrorString44 = {
        .dataOrig = &OD_RAM.x402C_serviceErrorString44[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402D_serviceErrorString45 = {
        .dataOrig = &OD_RAM.x402D_serviceErrorString45[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402E_serviceErrorString46 = {
        .dataOrig = &OD_RAM.x402E_serviceErrorString46[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_402F_serviceErrorString47 = {
        .dataOrig = &OD_RAM.x402F_serviceErrorString47[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4030_serviceErrorString48 = {
        .dataOrig = &OD_RAM.x4030_serviceErrorString48[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4031_serviceErrorString49 = {
        .dataOrig = &OD_RAM.x4031_serviceErrorString49[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4032_serviceErrorString50 = {
        .dataOrig = &OD_RAM.x4032_serviceErrorString50[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4033_serviceErrorString51 = {
        .dataOrig = &OD_RAM.x4033_serviceErrorString51[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4034_serviceErrorString52 = {
        .dataOrig = &OD_RAM.x4034_serviceErrorString52[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4035_serviceErrorString53 = {
        .dataOrig = &OD_RAM.x4035_serviceErrorString53[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4036_serviceErrorString54 = {
        .dataOrig = &OD_RAM.x4036_serviceErrorString54[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4037_serviceErrorString55 = {
        .dataOrig = &OD_RAM.x4037_serviceErrorString55[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4038_serviceErrorString56 = {
        .dataOrig = &OD_RAM.x4038_serviceErrorString56[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4039_serviceErrorString57 = {
        .dataOrig = &OD_RAM.x4039_serviceErrorString57[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403A_serviceErrorString58 = {
        .dataOrig = &OD_RAM.x403A_serviceErrorString58[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403B_serviceErrorString59 = {
        .dataOrig = &OD_RAM.x403B_serviceErrorString59[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403C_serviceErrorString60 = {
        .dataOrig = &OD_RAM.x403C_serviceErrorString60[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403D_serviceErrorString61 = {
        .dataOrig = &OD_RAM.x403D_serviceErrorString61[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403E_serviceErrorString62 = {
        .dataOrig = &OD_RAM.x403E_serviceErrorString62[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_403F_serviceErrorString63 = {
        .dataOrig = &OD_RAM.x403F_serviceErrorString63[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4040_serviceErrorString64 = {
        .dataOrig = &OD_RAM.x4040_serviceErrorString64[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4041_serviceErrorString65 = {
        .dataOrig = &OD_RAM.x4041_serviceErrorString65[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4042_serviceErrorString66 = {
        .dataOrig = &OD_RAM.x4042_serviceErrorString66[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4043_serviceErrorString67 = {
        .dataOrig = &OD_RAM.x4043_serviceErrorString67[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4044_serviceErrorString68 = {
        .dataOrig = &OD_RAM.x4044_serviceErrorString68[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4045_serviceErrorString69 = {
        .dataOrig = &OD_RAM.x4045_serviceErrorString69[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4046_serviceErrorString70 = {
        .dataOrig = &OD_RAM.x4046_serviceErrorString70[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4047_serviceErrorString71 = {
        .dataOrig = &OD_RAM.x4047_serviceErrorString71[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4048_serviceErrorString72 = {
        .dataOrig = &OD_RAM.x4048_serviceErrorString72[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4049_serviceErrorString73 = {
        .dataOrig = &OD_RAM.x4049_serviceErrorString73[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404A_serviceErrorString74 = {
        .dataOrig = &OD_RAM.x404A_serviceErrorString74[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404B_serviceErrorString75 = {
        .dataOrig = &OD_RAM.x404B_serviceErrorString75[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404C_serviceErrorString76 = {
        .dataOrig = &OD_RAM.x404C_serviceErrorString76[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404D_serviceErrorString77 = {
        .dataOrig = &OD_RAM.x404D_serviceErrorString77[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404E_serviceErrorString78 = {
        .dataOrig = &OD_RAM.x404E_serviceErrorString78[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_404F_serviceErrorString79 = {
        .dataOrig = &OD_RAM.x404F_serviceErrorString79[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4050_serviceErrorString80 = {
        .dataOrig = &OD_RAM.x4050_serviceErrorString80[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4051_serviceErrorString81 = {
        .dataOrig = &OD_RAM.x4051_serviceErrorString81[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4052_serviceErrorString82 = {
        .dataOrig = &OD_RAM.x4052_serviceErrorString82[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4053_serviceErrorString83 = {
        .dataOrig = &OD_RAM.x4053_serviceErrorString83[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4054_serviceErrorString84 = {
        .dataOrig = &OD_RAM.x4054_serviceErrorString84[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4055_serviceErrorString85 = {
        .dataOrig = &OD_RAM.x4055_serviceErrorString85[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4056_serviceErrorString86 = {
        .dataOrig = &OD_RAM.x4056_serviceErrorString86[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4057_serviceErrorString87 = {
        .dataOrig = &OD_RAM.x4057_serviceErrorString87[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4058_serviceErrorString88 = {
        .dataOrig = &OD_RAM.x4058_serviceErrorString88[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4059_serviceErrorString89 = {
        .dataOrig = &OD_RAM.x4059_serviceErrorString89[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405A_serviceErrorString90 = {
        .dataOrig = &OD_RAM.x405A_serviceErrorString90[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405B_serviceErrorString91 = {
        .dataOrig = &OD_RAM.x405B_serviceErrorString91[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405C_serviceErrorString92 = {
        .dataOrig = &OD_RAM.x405C_serviceErrorString92[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405D_serviceErrorString93 = {
        .dataOrig = &OD_RAM.x405D_serviceErrorString93[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405E_serviceErrorString94 = {
        .dataOrig = &OD_RAM.x405E_serviceErrorString94[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_405F_serviceErrorString95 = {
        .dataOrig = &OD_RAM.x405F_serviceErrorString95[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4060_serviceErrorString96 = {
        .dataOrig = &OD_RAM.x4060_serviceErrorString96[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4061_serviceErrorString97 = {
        .dataOrig = &OD_RAM.x4061_serviceErrorString97[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4062_serviceErrorString98 = {
        .dataOrig = &OD_RAM.x4062_serviceErrorString98[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4063_serviceErrorString99 = {
        .dataOrig = &OD_RAM.x4063_serviceErrorString99[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4064_serviceErrorString100 = {
        .dataOrig = &OD_RAM.x4064_serviceErrorString100[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4065_serviceErrorString101 = {
        .dataOrig = &OD_RAM.x4065_serviceErrorString101[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4066_serviceErrorString102 = {
        .dataOrig = &OD_RAM.x4066_serviceErrorString102[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4067_serviceErrorString103 = {
        .dataOrig = &OD_RAM.x4067_serviceErrorString103[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4068_serviceErrorString104 = {
        .dataOrig = &OD_RAM.x4068_serviceErrorString104[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4069_serviceErrorString105 = {
        .dataOrig = &OD_RAM.x4069_serviceErrorString105[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406A_serviceErrorString106 = {
        .dataOrig = &OD_RAM.x406A_serviceErrorString106[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406B_serviceErrorString107 = {
        .dataOrig = &OD_RAM.x406B_serviceErrorString107[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406C_serviceErrorString108 = {
        .dataOrig = &OD_RAM.x406C_serviceErrorString108[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406D_serviceErrorString109 = {
        .dataOrig = &OD_RAM.x406D_serviceErrorString109[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406E_serviceErrorString110 = {
        .dataOrig = &OD_RAM.x406E_serviceErrorString110[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_406F_serviceErrorString111 = {
        .dataOrig = &OD_RAM.x406F_serviceErrorString111[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4070_serviceErrorString112 = {
        .dataOrig = &OD_RAM.x4070_serviceErrorString112[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4071_serviceErrorString113 = {
        .dataOrig = &OD_RAM.x4071_serviceErrorString113[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4072_serviceErrorString114 = {
        .dataOrig = &OD_RAM.x4072_serviceErrorString114[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4073_serviceErrorString115 = {
        .dataOrig = &OD_RAM.x4073_serviceErrorString115[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4074_serviceErrorString116 = {
        .dataOrig = &OD_RAM.x4074_serviceErrorString116[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4075_serviceErrorString117 = {
        .dataOrig = &OD_RAM.x4075_serviceErrorString117[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4076_serviceErrorString118 = {
        .dataOrig = &OD_RAM.x4076_serviceErrorString118[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4077_serviceErrorString119 = {
        .dataOrig = &OD_RAM.x4077_serviceErrorString119[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4078_serviceErrorString120 = {
        .dataOrig = &OD_RAM.x4078_serviceErrorString120[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_4079_serviceErrorString121 = {
        .dataOrig = &OD_RAM.x4079_serviceErrorString121[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407A_serviceErrorString122 = {
        .dataOrig = &OD_RAM.x407A_serviceErrorString122[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407B_serviceErrorString123 = {
        .dataOrig = &OD_RAM.x407B_serviceErrorString123[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407C_serviceErrorString124 = {
        .dataOrig = &OD_RAM.x407C_serviceErrorString124[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407D_serviceErrorString125 = {
        .dataOrig = &OD_RAM.x407D_serviceErrorString125[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407E_serviceErrorString126 = {
        .dataOrig = &OD_RAM.x407E_serviceErrorString126[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_407F_serviceErrorString127 = {
        .dataOrig = &OD_RAM.x407F_serviceErrorString127[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 1
    },
    .o_6000_digitalInputs1 = {
        .dataOrig0 = &OD_RAM.x6000_digitalInputs1_sub0,
        .dataOrig = &OD_RAM.x6000_digitalInputs1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6200_digitalInputs2 = {
        .dataOrig0 = &OD_RAM.x6200_digitalInputs2_sub0,
        .dataOrig = &OD_RAM.x6200_digitalInputs2[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6401_analogInputs = {
        .dataOrig0 = &OD_RAM.x6401_analogInputs_sub0,
        .dataOrig = &OD_RAM.x6401_analogInputs[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x100C, 0x01, ODT_VAR, &ODObjs.o_100C_guardTime, NULL},
    {0x100D, 0x01, ODT_VAR, &ODObjs.o_100D_lifeTimeFactor, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x07, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x07, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x07, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x07, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x1F80, 0x01, ODT_VAR, &ODObjs.o_1F80_NMTStartup, NULL},
    {0x2000, 0x04, ODT_ARR, &ODObjs.o_2000_actualValues, NULL},
    {0x2010, 0x03, ODT_ARR, &ODObjs.o_2010_alarmStateRegister, NULL},
    {0x2011, 0x04, ODT_ARR, &ODObjs.o_2011_operatingStateRegister, NULL},
    {0x2012, 0x04, ODT_ARR, &ODObjs.o_2012_configurationStateRegister, NULL},
    {0x2013, 0x11, ODT_ARR, &ODObjs.o_2013_vendorStateRegister, NULL},
    {0x2020, 0x01, ODT_VAR, &ODObjs.o_2020_deviceStateRegister, NULL},
    {0x205B, 0x02, ODT_ARR, &ODObjs.o_205B_maintananceStateRegister, NULL},
    {0x2100, 0x04, ODT_ARR, &ODObjs.o_2100_minimumValueOf2500H, NULL},
    {0x2110, 0x04, ODT_ARR, &ODObjs.o_2110_maximumValueOf2500H, NULL},
    {0x2120, 0x04, ODT_ARR, &ODObjs.o_2120_stepWidthOf2500H, NULL},
    {0x2500, 0x04, ODT_ARR, &ODObjs.o_2500_setppoints, NULL},
    {0x2511, 0x04, ODT_ARR, &ODObjs.o_2511_operatingControlRegister, NULL},
    {0x2520, 0x01, ODT_VAR, &ODObjs.o_2520_deviceControlRegister, NULL},
    {0x2600, 0x04, ODT_ARR, &ODObjs.o_2600_minimumLimitsOf2000H, NULL},
    {0x2610, 0x04, ODT_ARR, &ODObjs.o_2610_maximumLimitsOf2000H, NULL},
    {0x2621, 0x08, ODT_ARR, &ODObjs.o_2621_configurationParameter, NULL},
    {0x2622, 0x01, ODT_VAR, &ODObjs.o_2622_presetOperatingCtrl, NULL},
    {0x2670, 0x06, ODT_ARR, &ODObjs.o_2670_runLogData, NULL},
    {0x3030, 0x01, ODT_VAR, &ODObjs.o_3030_numberOfServiceErrorStrings, NULL},
    {0x3031, 0x06, ODT_ARR, &ODObjs.o_3031_serviceErrorStringLanguageSupport, NULL},
    {0x3032, 0x01, ODT_VAR, &ODObjs.o_3032_setServiceErrorLanguage, NULL},
    {0x4000, 0x01, ODT_VAR, &ODObjs.o_4000_serviceErrorString0, NULL},
    {0x4001, 0x01, ODT_VAR, &ODObjs.o_4001_serviceErrorString1, NULL},
    {0x4002, 0x01, ODT_VAR, &ODObjs.o_4002_serviceErrorString2, NULL},
    {0x4003, 0x01, ODT_VAR, &ODObjs.o_4003_serviceErrorString3, NULL},
    {0x4004, 0x01, ODT_VAR, &ODObjs.o_4004_serviceErrorString4, NULL},
    {0x4005, 0x01, ODT_VAR, &ODObjs.o_4005_serviceErrorString5, NULL},
    {0x4006, 0x01, ODT_VAR, &ODObjs.o_4006_serviceErrorString6, NULL},
    {0x4007, 0x01, ODT_VAR, &ODObjs.o_4007_serviceErrorString7, NULL},
    {0x4008, 0x01, ODT_VAR, &ODObjs.o_4008_serviceErrorString8, NULL},
    {0x4009, 0x01, ODT_VAR, &ODObjs.o_4009_serviceErrorString9, NULL},
    {0x400A, 0x01, ODT_VAR, &ODObjs.o_400A_serviceErrorString10, NULL},
    {0x400B, 0x01, ODT_VAR, &ODObjs.o_400B_serviceErrorString11, NULL},
    {0x400C, 0x01, ODT_VAR, &ODObjs.o_400C_serviceErrorString12, NULL},
    {0x400D, 0x01, ODT_VAR, &ODObjs.o_400D_serviceErrorString13, NULL},
    {0x400E, 0x01, ODT_VAR, &ODObjs.o_400E_serviceErrorString14, NULL},
    {0x400F, 0x01, ODT_VAR, &ODObjs.o_400F_serviceErrorString15, NULL},
    {0x4010, 0x01, ODT_VAR, &ODObjs.o_4010_serviceErrorString16, NULL},
    {0x4011, 0x01, ODT_VAR, &ODObjs.o_4011_serviceErrorString17, NULL},
    {0x4012, 0x01, ODT_VAR, &ODObjs.o_4012_serviceErrorString18, NULL},
    {0x4013, 0x01, ODT_VAR, &ODObjs.o_4013_serviceErrorString19, NULL},
    {0x4014, 0x01, ODT_VAR, &ODObjs.o_4014_serviceErrorString20, NULL},
    {0x4015, 0x01, ODT_VAR, &ODObjs.o_4015_serviceErrorString21, NULL},
    {0x4016, 0x01, ODT_VAR, &ODObjs.o_4016_serviceErrorString22, NULL},
    {0x4017, 0x01, ODT_VAR, &ODObjs.o_4017_serviceErrorString23, NULL},
    {0x4018, 0x01, ODT_VAR, &ODObjs.o_4018_serviceErrorString24, NULL},
    {0x4019, 0x01, ODT_VAR, &ODObjs.o_4019_serviceErrorString25, NULL},
    {0x401A, 0x01, ODT_VAR, &ODObjs.o_401A_serviceErrorString26, NULL},
    {0x401B, 0x01, ODT_VAR, &ODObjs.o_401B_serviceErrorString27, NULL},
    {0x401C, 0x01, ODT_VAR, &ODObjs.o_401C_serviceErrorString28, NULL},
    {0x401D, 0x01, ODT_VAR, &ODObjs.o_401D_serviceErrorString29, NULL},
    {0x401E, 0x01, ODT_VAR, &ODObjs.o_401E_serviceErrorString30, NULL},
    {0x401F, 0x01, ODT_VAR, &ODObjs.o_401F_serviceErrorString31, NULL},
    {0x4020, 0x01, ODT_VAR, &ODObjs.o_4020_serviceErrorString32, NULL},
    {0x4021, 0x01, ODT_VAR, &ODObjs.o_4021_serviceErrorString33, NULL},
    {0x4022, 0x01, ODT_VAR, &ODObjs.o_4022_serviceErrorString34, NULL},
    {0x4023, 0x01, ODT_VAR, &ODObjs.o_4023_serviceErrorString35, NULL},
    {0x4024, 0x01, ODT_VAR, &ODObjs.o_4024_serviceErrorString36, NULL},
    {0x4025, 0x01, ODT_VAR, &ODObjs.o_4025_serviceErrorString37, NULL},
    {0x4026, 0x01, ODT_VAR, &ODObjs.o_4026_serviceErrorString38, NULL},
    {0x4027, 0x01, ODT_VAR, &ODObjs.o_4027_serviceErrorString39, NULL},
    {0x4028, 0x01, ODT_VAR, &ODObjs.o_4028_serviceErrorString40, NULL},
    {0x4029, 0x01, ODT_VAR, &ODObjs.o_4029_serviceErrorString41, NULL},
    {0x402A, 0x01, ODT_VAR, &ODObjs.o_402A_serviceErrorString42, NULL},
    {0x402B, 0x01, ODT_VAR, &ODObjs.o_402B_serviceErrorString43, NULL},
    {0x402C, 0x01, ODT_VAR, &ODObjs.o_402C_serviceErrorString44, NULL},
    {0x402D, 0x01, ODT_VAR, &ODObjs.o_402D_serviceErrorString45, NULL},
    {0x402E, 0x01, ODT_VAR, &ODObjs.o_402E_serviceErrorString46, NULL},
    {0x402F, 0x01, ODT_VAR, &ODObjs.o_402F_serviceErrorString47, NULL},
    {0x4030, 0x01, ODT_VAR, &ODObjs.o_4030_serviceErrorString48, NULL},
    {0x4031, 0x01, ODT_VAR, &ODObjs.o_4031_serviceErrorString49, NULL},
    {0x4032, 0x01, ODT_VAR, &ODObjs.o_4032_serviceErrorString50, NULL},
    {0x4033, 0x01, ODT_VAR, &ODObjs.o_4033_serviceErrorString51, NULL},
    {0x4034, 0x01, ODT_VAR, &ODObjs.o_4034_serviceErrorString52, NULL},
    {0x4035, 0x01, ODT_VAR, &ODObjs.o_4035_serviceErrorString53, NULL},
    {0x4036, 0x01, ODT_VAR, &ODObjs.o_4036_serviceErrorString54, NULL},
    {0x4037, 0x01, ODT_VAR, &ODObjs.o_4037_serviceErrorString55, NULL},
    {0x4038, 0x01, ODT_VAR, &ODObjs.o_4038_serviceErrorString56, NULL},
    {0x4039, 0x01, ODT_VAR, &ODObjs.o_4039_serviceErrorString57, NULL},
    {0x403A, 0x01, ODT_VAR, &ODObjs.o_403A_serviceErrorString58, NULL},
    {0x403B, 0x01, ODT_VAR, &ODObjs.o_403B_serviceErrorString59, NULL},
    {0x403C, 0x01, ODT_VAR, &ODObjs.o_403C_serviceErrorString60, NULL},
    {0x403D, 0x01, ODT_VAR, &ODObjs.o_403D_serviceErrorString61, NULL},
    {0x403E, 0x01, ODT_VAR, &ODObjs.o_403E_serviceErrorString62, NULL},
    {0x403F, 0x01, ODT_VAR, &ODObjs.o_403F_serviceErrorString63, NULL},
    {0x4040, 0x01, ODT_VAR, &ODObjs.o_4040_serviceErrorString64, NULL},
    {0x4041, 0x01, ODT_VAR, &ODObjs.o_4041_serviceErrorString65, NULL},
    {0x4042, 0x01, ODT_VAR, &ODObjs.o_4042_serviceErrorString66, NULL},
    {0x4043, 0x01, ODT_VAR, &ODObjs.o_4043_serviceErrorString67, NULL},
    {0x4044, 0x01, ODT_VAR, &ODObjs.o_4044_serviceErrorString68, NULL},
    {0x4045, 0x01, ODT_VAR, &ODObjs.o_4045_serviceErrorString69, NULL},
    {0x4046, 0x01, ODT_VAR, &ODObjs.o_4046_serviceErrorString70, NULL},
    {0x4047, 0x01, ODT_VAR, &ODObjs.o_4047_serviceErrorString71, NULL},
    {0x4048, 0x01, ODT_VAR, &ODObjs.o_4048_serviceErrorString72, NULL},
    {0x4049, 0x01, ODT_VAR, &ODObjs.o_4049_serviceErrorString73, NULL},
    {0x404A, 0x01, ODT_VAR, &ODObjs.o_404A_serviceErrorString74, NULL},
    {0x404B, 0x01, ODT_VAR, &ODObjs.o_404B_serviceErrorString75, NULL},
    {0x404C, 0x01, ODT_VAR, &ODObjs.o_404C_serviceErrorString76, NULL},
    {0x404D, 0x01, ODT_VAR, &ODObjs.o_404D_serviceErrorString77, NULL},
    {0x404E, 0x01, ODT_VAR, &ODObjs.o_404E_serviceErrorString78, NULL},
    {0x404F, 0x01, ODT_VAR, &ODObjs.o_404F_serviceErrorString79, NULL},
    {0x4050, 0x01, ODT_VAR, &ODObjs.o_4050_serviceErrorString80, NULL},
    {0x4051, 0x01, ODT_VAR, &ODObjs.o_4051_serviceErrorString81, NULL},
    {0x4052, 0x01, ODT_VAR, &ODObjs.o_4052_serviceErrorString82, NULL},
    {0x4053, 0x01, ODT_VAR, &ODObjs.o_4053_serviceErrorString83, NULL},
    {0x4054, 0x01, ODT_VAR, &ODObjs.o_4054_serviceErrorString84, NULL},
    {0x4055, 0x01, ODT_VAR, &ODObjs.o_4055_serviceErrorString85, NULL},
    {0x4056, 0x01, ODT_VAR, &ODObjs.o_4056_serviceErrorString86, NULL},
    {0x4057, 0x01, ODT_VAR, &ODObjs.o_4057_serviceErrorString87, NULL},
    {0x4058, 0x01, ODT_VAR, &ODObjs.o_4058_serviceErrorString88, NULL},
    {0x4059, 0x01, ODT_VAR, &ODObjs.o_4059_serviceErrorString89, NULL},
    {0x405A, 0x01, ODT_VAR, &ODObjs.o_405A_serviceErrorString90, NULL},
    {0x405B, 0x01, ODT_VAR, &ODObjs.o_405B_serviceErrorString91, NULL},
    {0x405C, 0x01, ODT_VAR, &ODObjs.o_405C_serviceErrorString92, NULL},
    {0x405D, 0x01, ODT_VAR, &ODObjs.o_405D_serviceErrorString93, NULL},
    {0x405E, 0x01, ODT_VAR, &ODObjs.o_405E_serviceErrorString94, NULL},
    {0x405F, 0x01, ODT_VAR, &ODObjs.o_405F_serviceErrorString95, NULL},
    {0x4060, 0x01, ODT_VAR, &ODObjs.o_4060_serviceErrorString96, NULL},
    {0x4061, 0x01, ODT_VAR, &ODObjs.o_4061_serviceErrorString97, NULL},
    {0x4062, 0x01, ODT_VAR, &ODObjs.o_4062_serviceErrorString98, NULL},
    {0x4063, 0x01, ODT_VAR, &ODObjs.o_4063_serviceErrorString99, NULL},
    {0x4064, 0x01, ODT_VAR, &ODObjs.o_4064_serviceErrorString100, NULL},
    {0x4065, 0x01, ODT_VAR, &ODObjs.o_4065_serviceErrorString101, NULL},
    {0x4066, 0x01, ODT_VAR, &ODObjs.o_4066_serviceErrorString102, NULL},
    {0x4067, 0x01, ODT_VAR, &ODObjs.o_4067_serviceErrorString103, NULL},
    {0x4068, 0x01, ODT_VAR, &ODObjs.o_4068_serviceErrorString104, NULL},
    {0x4069, 0x01, ODT_VAR, &ODObjs.o_4069_serviceErrorString105, NULL},
    {0x406A, 0x01, ODT_VAR, &ODObjs.o_406A_serviceErrorString106, NULL},
    {0x406B, 0x01, ODT_VAR, &ODObjs.o_406B_serviceErrorString107, NULL},
    {0x406C, 0x01, ODT_VAR, &ODObjs.o_406C_serviceErrorString108, NULL},
    {0x406D, 0x01, ODT_VAR, &ODObjs.o_406D_serviceErrorString109, NULL},
    {0x406E, 0x01, ODT_VAR, &ODObjs.o_406E_serviceErrorString110, NULL},
    {0x406F, 0x01, ODT_VAR, &ODObjs.o_406F_serviceErrorString111, NULL},
    {0x4070, 0x01, ODT_VAR, &ODObjs.o_4070_serviceErrorString112, NULL},
    {0x4071, 0x01, ODT_VAR, &ODObjs.o_4071_serviceErrorString113, NULL},
    {0x4072, 0x01, ODT_VAR, &ODObjs.o_4072_serviceErrorString114, NULL},
    {0x4073, 0x01, ODT_VAR, &ODObjs.o_4073_serviceErrorString115, NULL},
    {0x4074, 0x01, ODT_VAR, &ODObjs.o_4074_serviceErrorString116, NULL},
    {0x4075, 0x01, ODT_VAR, &ODObjs.o_4075_serviceErrorString117, NULL},
    {0x4076, 0x01, ODT_VAR, &ODObjs.o_4076_serviceErrorString118, NULL},
    {0x4077, 0x01, ODT_VAR, &ODObjs.o_4077_serviceErrorString119, NULL},
    {0x4078, 0x01, ODT_VAR, &ODObjs.o_4078_serviceErrorString120, NULL},
    {0x4079, 0x01, ODT_VAR, &ODObjs.o_4079_serviceErrorString121, NULL},
    {0x407A, 0x01, ODT_VAR, &ODObjs.o_407A_serviceErrorString122, NULL},
    {0x407B, 0x01, ODT_VAR, &ODObjs.o_407B_serviceErrorString123, NULL},
    {0x407C, 0x01, ODT_VAR, &ODObjs.o_407C_serviceErrorString124, NULL},
    {0x407D, 0x01, ODT_VAR, &ODObjs.o_407D_serviceErrorString125, NULL},
    {0x407E, 0x01, ODT_VAR, &ODObjs.o_407E_serviceErrorString126, NULL},
    {0x407F, 0x01, ODT_VAR, &ODObjs.o_407F_serviceErrorString127, NULL},
    {0x6000, 0x07, ODT_ARR, &ODObjs.o_6000_digitalInputs1, NULL},
    {0x6200, 0x04, ODT_ARR, &ODObjs.o_6200_digitalInputs2, NULL},
    {0x6401, 0x07, ODT_ARR, &ODObjs.o_6401_analogInputs, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
