/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-36-gb1372cb

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: inkline.xdd
        File Version: 1.0

        Created:      10.08.2023 10:07:00
        Created By:   
        Modified:     24.10.2023 09:06:06
        Modified By:  

    Device Info:
        Vendor Name:  technotrans SE
        Vendor ID:    268
        Product Name: Inkline V2.0
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
#define OD_CNT_ARR_2000 3
#define OD_CNT_ARR_2010 2
#define OD_CNT_ARR_2011 3
#define OD_CNT_ARR_2012 3
#define OD_CNT_ARR_2013 16
#define OD_CNT_ARR_205B 1
#define OD_CNT_ARR_2100 3
#define OD_CNT_ARR_2110 3
#define OD_CNT_ARR_2120 3
#define OD_CNT_ARR_2500 3
#define OD_CNT_ARR_2511 3
#define OD_CNT_ARR_2600 3
#define OD_CNT_ARR_2610 3
#define OD_CNT_ARR_2621 7
#define OD_CNT_ARR_2670 5
#define OD_CNT_ARR_3031 5
#define OD_CNT_ARR_6000 6
#define OD_CNT_ARR_6200 3
#define OD_CNT_ARR_6401 6


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint16_t x100B_guardTime;
    uint8_t x100C_lifeTimeFactor;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint32_t x1F80_NMTStartup;
    uint8_t x2000_actualValues_sub0;
    uint8_t x2010_alarmStateRegister_sub0;
    uint8_t x2010_alarmStateRegister[OD_CNT_ARR_2010];
    uint8_t x2011_operatingStateRegister_sub0;
    uint8_t x2011_operatingStateRegister[OD_CNT_ARR_2011];
    uint8_t x2012_configurationStateRegister_sub0;
    uint8_t x2012_configurationStateRegister[OD_CNT_ARR_2012];
    uint8_t x2013_vendorStateRegister_sub0;
    uint8_t x2013_vendorStateRegister[OD_CNT_ARR_2013];
    uint8_t x2020_deviceStateRegister;
    uint8_t x205B_maintananceStateRegister_sub0;
    uint8_t x205B_maintananceStateRegister[OD_CNT_ARR_205B];
    uint8_t x2100_minimumValueOf2500H_sub0;
    int16_t x2100_minimumValueOf2500H[OD_CNT_ARR_2100];
    uint8_t x2110_maximumValueOf2500H_sub0;
    int16_t x2110_maximumValueOf2500H[OD_CNT_ARR_2110];
    uint8_t x2120_stepWidthOf2500H_sub0;
    int16_t x2120_stepWidthOf2500H[OD_CNT_ARR_2120];
    uint8_t x2500_setppoints_sub0;
    int16_t x2500_setppoints[OD_CNT_ARR_2500];
    uint8_t x2511_operatingControlRegister_sub0;
    uint8_t x2511_operatingControlRegister[OD_CNT_ARR_2511];
    uint8_t x2520_deviceControlRegister;
    uint8_t x2600_minimumLimitsOf2000H_sub0;
    uint8_t x2610_maximumLimitsOf2000H_sub0;
    uint8_t x2621_configurationParameter_sub0;
    int16_t x2621_configurationParameter[OD_CNT_ARR_2621];
    uint16_t x2622_presetOperatingCtrl;
    uint8_t x2670_runLogData_sub0;
    uint16_t x3030_numberOfServiceErrorStrings;
    uint8_t x3031_serviceErrorStringLanguageSupport_sub0;
    uint8_t x3031_serviceErrorStringLanguageSupport[OD_CNT_ARR_3031];
    uint16_t x3032_setServiceErrorLanguage;
    char x4000_serviceErrorString0[2];
    char x4001_serviceErrorString1[2];
    char x4002_serviceErrorString2[2];
    char x4003_serviceErrorString3[2];
    char x4004_serviceErrorString4[2];
    char x4005_serviceErrorString5[2];
    char x4006_serviceErrorString6[2];
    char x4007_serviceErrorString7[2];
    char x4008_serviceErrorString8[2];
    char x4009_serviceErrorString9[2];
    char x400A_serviceErrorString10[2];
    char x400B_serviceErrorString11[2];
    char x400C_serviceErrorString12[2];
    char x400D_serviceErrorString13[2];
    char x400E_serviceErrorString14[2];
    char x400F_serviceErrorString15[2];
    char x4010_serviceErrorString16[2];
    char x4011_serviceErrorString17[2];
    char x4012_serviceErrorString18[2];
    char x4013_serviceErrorString19[2];
    char x4014_serviceErrorString20[2];
    char x4015_serviceErrorString21[2];
    char x4016_serviceErrorString22[2];
    char x4017_serviceErrorString23[2];
    char x4018_serviceErrorString24[2];
    char x4019_serviceErrorString25[2];
    char x401A_serviceErrorString26[2];
    char x401B_serviceErrorString27[2];
    char x401C_serviceErrorString28[2];
    char x401D_serviceErrorString29[2];
    char x401E_serviceErrorString30[2];
    char x401F_serviceErrorString31[2];
    char x4020_serviceErrorString32[2];
    char x4021_serviceErrorString33[2];
    char x4022_serviceErrorString34[2];
    char x4023_serviceErrorString35[2];
    char x4024_serviceErrorString36[2];
    char x4025_serviceErrorString37[2];
    char x4026_serviceErrorString38[2];
    char x4027_serviceErrorString39[2];
    char x4028_serviceErrorString40[2];
    char x4029_serviceErrorString41[2];
    char x402A_serviceErrorString42[2];
    char x402B_serviceErrorString43[2];
    char x402C_serviceErrorString44[2];
    char x402D_serviceErrorString45[2];
    char x402E_serviceErrorString46[2];
    char x402F_serviceErrorString47[2];
    char x4030_serviceErrorString48[2];
    char x4031_serviceErrorString49[2];
    char x4032_serviceErrorString50[2];
    char x4033_serviceErrorString51[2];
    char x4034_serviceErrorString52[2];
    char x4035_serviceErrorString53[2];
    char x4036_serviceErrorString54[2];
    char x4037_serviceErrorString55[2];
    char x4038_serviceErrorString56[2];
    char x4039_serviceErrorString57[2];
    char x403A_serviceErrorString58[2];
    char x403B_serviceErrorString59[2];
    char x403C_serviceErrorString60[2];
    char x403D_serviceErrorString61[2];
    char x403E_serviceErrorString62[2];
    char x403F_serviceErrorString63[2];
    char x4040_serviceErrorString64[2];
    char x4041_serviceErrorString65[2];
    char x4042_serviceErrorString66[2];
    char x4043_serviceErrorString67[2];
    char x4044_serviceErrorString68[2];
    char x4045_serviceErrorString69[2];
    char x4046_serviceErrorString70[2];
    char x4047_serviceErrorString71[2];
    char x4048_serviceErrorString72[2];
    char x4049_serviceErrorString73[2];
    char x404A_serviceErrorString74[2];
    char x404B_serviceErrorString75[2];
    char x404C_serviceErrorString76[2];
    char x404D_serviceErrorString77[2];
    char x404E_serviceErrorString78[2];
    char x404F_serviceErrorString79[2];
    char x4050_serviceErrorString80[2];
    char x4051_serviceErrorString81[2];
    char x4052_serviceErrorString82[2];
    char x4053_serviceErrorString83[2];
    char x4054_serviceErrorString84[2];
    char x4055_serviceErrorString85[2];
    char x4056_serviceErrorString86[2];
    char x4057_serviceErrorString87[2];
    char x4058_serviceErrorString88[2];
    char x4059_serviceErrorString89[2];
    char x405A_serviceErrorString90[2];
    char x405B_serviceErrorString91[2];
    char x405C_serviceErrorString92[2];
    char x405D_serviceErrorString93[2];
    char x405E_serviceErrorString94[2];
    char x405F_serviceErrorString95[2];
    char x4060_serviceErrorString96[2];
    char x4061_serviceErrorString97[2];
    char x4062_serviceErrorString98[2];
    char x4063_serviceErrorString99[2];
    char x4064_serviceErrorString100[2];
    char x4065_serviceErrorString101[2];
    char x4066_serviceErrorString102[2];
    char x4067_serviceErrorString103[2];
    char x4068_serviceErrorString104[2];
    char x4069_serviceErrorString105[2];
    char x406A_serviceErrorString106[2];
    char x406B_serviceErrorString107[2];
    char x406C_serviceErrorString108[2];
    char x406D_serviceErrorString109[2];
    char x406E_serviceErrorString110[2];
    char x406F_serviceErrorString111[2];
    char x4070_serviceErrorString112[2];
    char x4071_serviceErrorString113[2];
    char x4072_serviceErrorString114[2];
    char x4073_serviceErrorString115[2];
    char x4074_serviceErrorString116[2];
    char x4075_serviceErrorString117[2];
    char x4076_serviceErrorString118[2];
    char x4077_serviceErrorString119[2];
    char x4078_serviceErrorString120[2];
    char x4079_serviceErrorString121[2];
    char x407A_serviceErrorString122[2];
    char x407B_serviceErrorString123[2];
    char x407C_serviceErrorString124[2];
    char x407D_serviceErrorString125[2];
    char x407E_serviceErrorString126[2];
    char x407F_serviceErrorString127[2];
    uint8_t x6000_digitalInputs_sub0;
    uint8_t x6000_digitalInputs[OD_CNT_ARR_6000];
    uint8_t x6200_digitalInputs_sub0;
    uint8_t x6200_digitalInputs[OD_CNT_ARR_6200];
    uint8_t x6401_analogInputs_sub0;
    int16_t x6401_analogInputs[OD_CNT_ARR_6401];
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H100B &OD->list[6]
#define OD_ENTRY_H100C &OD->list[7]
#define OD_ENTRY_H1010 &OD->list[8]
#define OD_ENTRY_H1011 &OD->list[9]
#define OD_ENTRY_H1012 &OD->list[10]
#define OD_ENTRY_H1014 &OD->list[11]
#define OD_ENTRY_H1015 &OD->list[12]
#define OD_ENTRY_H1016 &OD->list[13]
#define OD_ENTRY_H1017 &OD->list[14]
#define OD_ENTRY_H1018 &OD->list[15]
#define OD_ENTRY_H1019 &OD->list[16]
#define OD_ENTRY_H1200 &OD->list[17]
#define OD_ENTRY_H1280 &OD->list[18]
#define OD_ENTRY_H1400 &OD->list[19]
#define OD_ENTRY_H1401 &OD->list[20]
#define OD_ENTRY_H1402 &OD->list[21]
#define OD_ENTRY_H1403 &OD->list[22]
#define OD_ENTRY_H1600 &OD->list[23]
#define OD_ENTRY_H1601 &OD->list[24]
#define OD_ENTRY_H1602 &OD->list[25]
#define OD_ENTRY_H1603 &OD->list[26]
#define OD_ENTRY_H1800 &OD->list[27]
#define OD_ENTRY_H1801 &OD->list[28]
#define OD_ENTRY_H1802 &OD->list[29]
#define OD_ENTRY_H1803 &OD->list[30]
#define OD_ENTRY_H1A00 &OD->list[31]
#define OD_ENTRY_H1A01 &OD->list[32]
#define OD_ENTRY_H1A02 &OD->list[33]
#define OD_ENTRY_H1A03 &OD->list[34]
#define OD_ENTRY_H1F80 &OD->list[35]
#define OD_ENTRY_H2000 &OD->list[36]
#define OD_ENTRY_H2010 &OD->list[37]
#define OD_ENTRY_H2011 &OD->list[38]
#define OD_ENTRY_H2012 &OD->list[39]
#define OD_ENTRY_H2013 &OD->list[40]
#define OD_ENTRY_H2020 &OD->list[41]
#define OD_ENTRY_H205B &OD->list[42]
#define OD_ENTRY_H2100 &OD->list[43]
#define OD_ENTRY_H2110 &OD->list[44]
#define OD_ENTRY_H2120 &OD->list[45]
#define OD_ENTRY_H2500 &OD->list[46]
#define OD_ENTRY_H2511 &OD->list[47]
#define OD_ENTRY_H2520 &OD->list[48]
#define OD_ENTRY_H2600 &OD->list[49]
#define OD_ENTRY_H2610 &OD->list[50]
#define OD_ENTRY_H2621 &OD->list[51]
#define OD_ENTRY_H2622 &OD->list[52]
#define OD_ENTRY_H2670 &OD->list[53]
#define OD_ENTRY_H3030 &OD->list[54]
#define OD_ENTRY_H3031 &OD->list[55]
#define OD_ENTRY_H3032 &OD->list[56]
#define OD_ENTRY_H4000 &OD->list[57]
#define OD_ENTRY_H4001 &OD->list[58]
#define OD_ENTRY_H4002 &OD->list[59]
#define OD_ENTRY_H4003 &OD->list[60]
#define OD_ENTRY_H4004 &OD->list[61]
#define OD_ENTRY_H4005 &OD->list[62]
#define OD_ENTRY_H4006 &OD->list[63]
#define OD_ENTRY_H4007 &OD->list[64]
#define OD_ENTRY_H4008 &OD->list[65]
#define OD_ENTRY_H4009 &OD->list[66]
#define OD_ENTRY_H400A &OD->list[67]
#define OD_ENTRY_H400B &OD->list[68]
#define OD_ENTRY_H400C &OD->list[69]
#define OD_ENTRY_H400D &OD->list[70]
#define OD_ENTRY_H400E &OD->list[71]
#define OD_ENTRY_H400F &OD->list[72]
#define OD_ENTRY_H4010 &OD->list[73]
#define OD_ENTRY_H4011 &OD->list[74]
#define OD_ENTRY_H4012 &OD->list[75]
#define OD_ENTRY_H4013 &OD->list[76]
#define OD_ENTRY_H4014 &OD->list[77]
#define OD_ENTRY_H4015 &OD->list[78]
#define OD_ENTRY_H4016 &OD->list[79]
#define OD_ENTRY_H4017 &OD->list[80]
#define OD_ENTRY_H4018 &OD->list[81]
#define OD_ENTRY_H4019 &OD->list[82]
#define OD_ENTRY_H401A &OD->list[83]
#define OD_ENTRY_H401B &OD->list[84]
#define OD_ENTRY_H401C &OD->list[85]
#define OD_ENTRY_H401D &OD->list[86]
#define OD_ENTRY_H401E &OD->list[87]
#define OD_ENTRY_H401F &OD->list[88]
#define OD_ENTRY_H4020 &OD->list[89]
#define OD_ENTRY_H4021 &OD->list[90]
#define OD_ENTRY_H4022 &OD->list[91]
#define OD_ENTRY_H4023 &OD->list[92]
#define OD_ENTRY_H4024 &OD->list[93]
#define OD_ENTRY_H4025 &OD->list[94]
#define OD_ENTRY_H4026 &OD->list[95]
#define OD_ENTRY_H4027 &OD->list[96]
#define OD_ENTRY_H4028 &OD->list[97]
#define OD_ENTRY_H4029 &OD->list[98]
#define OD_ENTRY_H402A &OD->list[99]
#define OD_ENTRY_H402B &OD->list[100]
#define OD_ENTRY_H402C &OD->list[101]
#define OD_ENTRY_H402D &OD->list[102]
#define OD_ENTRY_H402E &OD->list[103]
#define OD_ENTRY_H402F &OD->list[104]
#define OD_ENTRY_H4030 &OD->list[105]
#define OD_ENTRY_H4031 &OD->list[106]
#define OD_ENTRY_H4032 &OD->list[107]
#define OD_ENTRY_H4033 &OD->list[108]
#define OD_ENTRY_H4034 &OD->list[109]
#define OD_ENTRY_H4035 &OD->list[110]
#define OD_ENTRY_H4036 &OD->list[111]
#define OD_ENTRY_H4037 &OD->list[112]
#define OD_ENTRY_H4038 &OD->list[113]
#define OD_ENTRY_H4039 &OD->list[114]
#define OD_ENTRY_H403A &OD->list[115]
#define OD_ENTRY_H403B &OD->list[116]
#define OD_ENTRY_H403C &OD->list[117]
#define OD_ENTRY_H403D &OD->list[118]
#define OD_ENTRY_H403E &OD->list[119]
#define OD_ENTRY_H403F &OD->list[120]
#define OD_ENTRY_H4040 &OD->list[121]
#define OD_ENTRY_H4041 &OD->list[122]
#define OD_ENTRY_H4042 &OD->list[123]
#define OD_ENTRY_H4043 &OD->list[124]
#define OD_ENTRY_H4044 &OD->list[125]
#define OD_ENTRY_H4045 &OD->list[126]
#define OD_ENTRY_H4046 &OD->list[127]
#define OD_ENTRY_H4047 &OD->list[128]
#define OD_ENTRY_H4048 &OD->list[129]
#define OD_ENTRY_H4049 &OD->list[130]
#define OD_ENTRY_H404A &OD->list[131]
#define OD_ENTRY_H404B &OD->list[132]
#define OD_ENTRY_H404C &OD->list[133]
#define OD_ENTRY_H404D &OD->list[134]
#define OD_ENTRY_H404E &OD->list[135]
#define OD_ENTRY_H404F &OD->list[136]
#define OD_ENTRY_H4050 &OD->list[137]
#define OD_ENTRY_H4051 &OD->list[138]
#define OD_ENTRY_H4052 &OD->list[139]
#define OD_ENTRY_H4053 &OD->list[140]
#define OD_ENTRY_H4054 &OD->list[141]
#define OD_ENTRY_H4055 &OD->list[142]
#define OD_ENTRY_H4056 &OD->list[143]
#define OD_ENTRY_H4057 &OD->list[144]
#define OD_ENTRY_H4058 &OD->list[145]
#define OD_ENTRY_H4059 &OD->list[146]
#define OD_ENTRY_H405A &OD->list[147]
#define OD_ENTRY_H405B &OD->list[148]
#define OD_ENTRY_H405C &OD->list[149]
#define OD_ENTRY_H405D &OD->list[150]
#define OD_ENTRY_H405E &OD->list[151]
#define OD_ENTRY_H405F &OD->list[152]
#define OD_ENTRY_H4060 &OD->list[153]
#define OD_ENTRY_H4061 &OD->list[154]
#define OD_ENTRY_H4062 &OD->list[155]
#define OD_ENTRY_H4063 &OD->list[156]
#define OD_ENTRY_H4064 &OD->list[157]
#define OD_ENTRY_H4065 &OD->list[158]
#define OD_ENTRY_H4066 &OD->list[159]
#define OD_ENTRY_H4067 &OD->list[160]
#define OD_ENTRY_H4068 &OD->list[161]
#define OD_ENTRY_H4069 &OD->list[162]
#define OD_ENTRY_H406A &OD->list[163]
#define OD_ENTRY_H406B &OD->list[164]
#define OD_ENTRY_H406C &OD->list[165]
#define OD_ENTRY_H406D &OD->list[166]
#define OD_ENTRY_H406E &OD->list[167]
#define OD_ENTRY_H406F &OD->list[168]
#define OD_ENTRY_H4070 &OD->list[169]
#define OD_ENTRY_H4071 &OD->list[170]
#define OD_ENTRY_H4072 &OD->list[171]
#define OD_ENTRY_H4073 &OD->list[172]
#define OD_ENTRY_H4074 &OD->list[173]
#define OD_ENTRY_H4075 &OD->list[174]
#define OD_ENTRY_H4076 &OD->list[175]
#define OD_ENTRY_H4077 &OD->list[176]
#define OD_ENTRY_H4078 &OD->list[177]
#define OD_ENTRY_H4079 &OD->list[178]
#define OD_ENTRY_H407A &OD->list[179]
#define OD_ENTRY_H407B &OD->list[180]
#define OD_ENTRY_H407C &OD->list[181]
#define OD_ENTRY_H407D &OD->list[182]
#define OD_ENTRY_H407E &OD->list[183]
#define OD_ENTRY_H407F &OD->list[184]
#define OD_ENTRY_H6000 &OD->list[185]
#define OD_ENTRY_H6200 &OD->list[186]
#define OD_ENTRY_H6401 &OD->list[187]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H100B_guardTime &OD->list[6]
#define OD_ENTRY_H100C_lifeTimeFactor &OD->list[7]
#define OD_ENTRY_H1010_storeParameters &OD->list[8]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[9]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[10]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[11]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[12]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[13]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[14]
#define OD_ENTRY_H1018_identity &OD->list[15]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[16]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[17]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[18]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[21]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[23]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[25]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[26]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[29]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[30]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[33]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[34]
#define OD_ENTRY_H1F80_NMTStartup &OD->list[35]
#define OD_ENTRY_H2000_actualValues &OD->list[36]
#define OD_ENTRY_H2010_alarmStateRegister &OD->list[37]
#define OD_ENTRY_H2011_operatingStateRegister &OD->list[38]
#define OD_ENTRY_H2012_configurationStateRegister &OD->list[39]
#define OD_ENTRY_H2013_vendorStateRegister &OD->list[40]
#define OD_ENTRY_H2020_deviceStateRegister &OD->list[41]
#define OD_ENTRY_H205B_maintananceStateRegister &OD->list[42]
#define OD_ENTRY_H2100_minimumValueOf2500H &OD->list[43]
#define OD_ENTRY_H2110_maximumValueOf2500H &OD->list[44]
#define OD_ENTRY_H2120_stepWidthOf2500H &OD->list[45]
#define OD_ENTRY_H2500_setppoints &OD->list[46]
#define OD_ENTRY_H2511_operatingControlRegister &OD->list[47]
#define OD_ENTRY_H2520_deviceControlRegister &OD->list[48]
#define OD_ENTRY_H2600_minimumLimitsOf2000H &OD->list[49]
#define OD_ENTRY_H2610_maximumLimitsOf2000H &OD->list[50]
#define OD_ENTRY_H2621_configurationParameter &OD->list[51]
#define OD_ENTRY_H2622_presetOperatingCtrl &OD->list[52]
#define OD_ENTRY_H2670_runLogData &OD->list[53]
#define OD_ENTRY_H3030_numberOfServiceErrorStrings &OD->list[54]
#define OD_ENTRY_H3031_serviceErrorStringLanguageSupport &OD->list[55]
#define OD_ENTRY_H3032_setServiceErrorLanguage &OD->list[56]
#define OD_ENTRY_H4000_serviceErrorString0 &OD->list[57]
#define OD_ENTRY_H4001_serviceErrorString1 &OD->list[58]
#define OD_ENTRY_H4002_serviceErrorString2 &OD->list[59]
#define OD_ENTRY_H4003_serviceErrorString3 &OD->list[60]
#define OD_ENTRY_H4004_serviceErrorString4 &OD->list[61]
#define OD_ENTRY_H4005_serviceErrorString5 &OD->list[62]
#define OD_ENTRY_H4006_serviceErrorString6 &OD->list[63]
#define OD_ENTRY_H4007_serviceErrorString7 &OD->list[64]
#define OD_ENTRY_H4008_serviceErrorString8 &OD->list[65]
#define OD_ENTRY_H4009_serviceErrorString9 &OD->list[66]
#define OD_ENTRY_H400A_serviceErrorString10 &OD->list[67]
#define OD_ENTRY_H400B_serviceErrorString11 &OD->list[68]
#define OD_ENTRY_H400C_serviceErrorString12 &OD->list[69]
#define OD_ENTRY_H400D_serviceErrorString13 &OD->list[70]
#define OD_ENTRY_H400E_serviceErrorString14 &OD->list[71]
#define OD_ENTRY_H400F_serviceErrorString15 &OD->list[72]
#define OD_ENTRY_H4010_serviceErrorString16 &OD->list[73]
#define OD_ENTRY_H4011_serviceErrorString17 &OD->list[74]
#define OD_ENTRY_H4012_serviceErrorString18 &OD->list[75]
#define OD_ENTRY_H4013_serviceErrorString19 &OD->list[76]
#define OD_ENTRY_H4014_serviceErrorString20 &OD->list[77]
#define OD_ENTRY_H4015_serviceErrorString21 &OD->list[78]
#define OD_ENTRY_H4016_serviceErrorString22 &OD->list[79]
#define OD_ENTRY_H4017_serviceErrorString23 &OD->list[80]
#define OD_ENTRY_H4018_serviceErrorString24 &OD->list[81]
#define OD_ENTRY_H4019_serviceErrorString25 &OD->list[82]
#define OD_ENTRY_H401A_serviceErrorString26 &OD->list[83]
#define OD_ENTRY_H401B_serviceErrorString27 &OD->list[84]
#define OD_ENTRY_H401C_serviceErrorString28 &OD->list[85]
#define OD_ENTRY_H401D_serviceErrorString29 &OD->list[86]
#define OD_ENTRY_H401E_serviceErrorString30 &OD->list[87]
#define OD_ENTRY_H401F_serviceErrorString31 &OD->list[88]
#define OD_ENTRY_H4020_serviceErrorString32 &OD->list[89]
#define OD_ENTRY_H4021_serviceErrorString33 &OD->list[90]
#define OD_ENTRY_H4022_serviceErrorString34 &OD->list[91]
#define OD_ENTRY_H4023_serviceErrorString35 &OD->list[92]
#define OD_ENTRY_H4024_serviceErrorString36 &OD->list[93]
#define OD_ENTRY_H4025_serviceErrorString37 &OD->list[94]
#define OD_ENTRY_H4026_serviceErrorString38 &OD->list[95]
#define OD_ENTRY_H4027_serviceErrorString39 &OD->list[96]
#define OD_ENTRY_H4028_serviceErrorString40 &OD->list[97]
#define OD_ENTRY_H4029_serviceErrorString41 &OD->list[98]
#define OD_ENTRY_H402A_serviceErrorString42 &OD->list[99]
#define OD_ENTRY_H402B_serviceErrorString43 &OD->list[100]
#define OD_ENTRY_H402C_serviceErrorString44 &OD->list[101]
#define OD_ENTRY_H402D_serviceErrorString45 &OD->list[102]
#define OD_ENTRY_H402E_serviceErrorString46 &OD->list[103]
#define OD_ENTRY_H402F_serviceErrorString47 &OD->list[104]
#define OD_ENTRY_H4030_serviceErrorString48 &OD->list[105]
#define OD_ENTRY_H4031_serviceErrorString49 &OD->list[106]
#define OD_ENTRY_H4032_serviceErrorString50 &OD->list[107]
#define OD_ENTRY_H4033_serviceErrorString51 &OD->list[108]
#define OD_ENTRY_H4034_serviceErrorString52 &OD->list[109]
#define OD_ENTRY_H4035_serviceErrorString53 &OD->list[110]
#define OD_ENTRY_H4036_serviceErrorString54 &OD->list[111]
#define OD_ENTRY_H4037_serviceErrorString55 &OD->list[112]
#define OD_ENTRY_H4038_serviceErrorString56 &OD->list[113]
#define OD_ENTRY_H4039_serviceErrorString57 &OD->list[114]
#define OD_ENTRY_H403A_serviceErrorString58 &OD->list[115]
#define OD_ENTRY_H403B_serviceErrorString59 &OD->list[116]
#define OD_ENTRY_H403C_serviceErrorString60 &OD->list[117]
#define OD_ENTRY_H403D_serviceErrorString61 &OD->list[118]
#define OD_ENTRY_H403E_serviceErrorString62 &OD->list[119]
#define OD_ENTRY_H403F_serviceErrorString63 &OD->list[120]
#define OD_ENTRY_H4040_serviceErrorString64 &OD->list[121]
#define OD_ENTRY_H4041_serviceErrorString65 &OD->list[122]
#define OD_ENTRY_H4042_serviceErrorString66 &OD->list[123]
#define OD_ENTRY_H4043_serviceErrorString67 &OD->list[124]
#define OD_ENTRY_H4044_serviceErrorString68 &OD->list[125]
#define OD_ENTRY_H4045_serviceErrorString69 &OD->list[126]
#define OD_ENTRY_H4046_serviceErrorString70 &OD->list[127]
#define OD_ENTRY_H4047_serviceErrorString71 &OD->list[128]
#define OD_ENTRY_H4048_serviceErrorString72 &OD->list[129]
#define OD_ENTRY_H4049_serviceErrorString73 &OD->list[130]
#define OD_ENTRY_H404A_serviceErrorString74 &OD->list[131]
#define OD_ENTRY_H404B_serviceErrorString75 &OD->list[132]
#define OD_ENTRY_H404C_serviceErrorString76 &OD->list[133]
#define OD_ENTRY_H404D_serviceErrorString77 &OD->list[134]
#define OD_ENTRY_H404E_serviceErrorString78 &OD->list[135]
#define OD_ENTRY_H404F_serviceErrorString79 &OD->list[136]
#define OD_ENTRY_H4050_serviceErrorString80 &OD->list[137]
#define OD_ENTRY_H4051_serviceErrorString81 &OD->list[138]
#define OD_ENTRY_H4052_serviceErrorString82 &OD->list[139]
#define OD_ENTRY_H4053_serviceErrorString83 &OD->list[140]
#define OD_ENTRY_H4054_serviceErrorString84 &OD->list[141]
#define OD_ENTRY_H4055_serviceErrorString85 &OD->list[142]
#define OD_ENTRY_H4056_serviceErrorString86 &OD->list[143]
#define OD_ENTRY_H4057_serviceErrorString87 &OD->list[144]
#define OD_ENTRY_H4058_serviceErrorString88 &OD->list[145]
#define OD_ENTRY_H4059_serviceErrorString89 &OD->list[146]
#define OD_ENTRY_H405A_serviceErrorString90 &OD->list[147]
#define OD_ENTRY_H405B_serviceErrorString91 &OD->list[148]
#define OD_ENTRY_H405C_serviceErrorString92 &OD->list[149]
#define OD_ENTRY_H405D_serviceErrorString93 &OD->list[150]
#define OD_ENTRY_H405E_serviceErrorString94 &OD->list[151]
#define OD_ENTRY_H405F_serviceErrorString95 &OD->list[152]
#define OD_ENTRY_H4060_serviceErrorString96 &OD->list[153]
#define OD_ENTRY_H4061_serviceErrorString97 &OD->list[154]
#define OD_ENTRY_H4062_serviceErrorString98 &OD->list[155]
#define OD_ENTRY_H4063_serviceErrorString99 &OD->list[156]
#define OD_ENTRY_H4064_serviceErrorString100 &OD->list[157]
#define OD_ENTRY_H4065_serviceErrorString101 &OD->list[158]
#define OD_ENTRY_H4066_serviceErrorString102 &OD->list[159]
#define OD_ENTRY_H4067_serviceErrorString103 &OD->list[160]
#define OD_ENTRY_H4068_serviceErrorString104 &OD->list[161]
#define OD_ENTRY_H4069_serviceErrorString105 &OD->list[162]
#define OD_ENTRY_H406A_serviceErrorString106 &OD->list[163]
#define OD_ENTRY_H406B_serviceErrorString107 &OD->list[164]
#define OD_ENTRY_H406C_serviceErrorString108 &OD->list[165]
#define OD_ENTRY_H406D_serviceErrorString109 &OD->list[166]
#define OD_ENTRY_H406E_serviceErrorString110 &OD->list[167]
#define OD_ENTRY_H406F_serviceErrorString111 &OD->list[168]
#define OD_ENTRY_H4070_serviceErrorString112 &OD->list[169]
#define OD_ENTRY_H4071_serviceErrorString113 &OD->list[170]
#define OD_ENTRY_H4072_serviceErrorString114 &OD->list[171]
#define OD_ENTRY_H4073_serviceErrorString115 &OD->list[172]
#define OD_ENTRY_H4074_serviceErrorString116 &OD->list[173]
#define OD_ENTRY_H4075_serviceErrorString117 &OD->list[174]
#define OD_ENTRY_H4076_serviceErrorString118 &OD->list[175]
#define OD_ENTRY_H4077_serviceErrorString119 &OD->list[176]
#define OD_ENTRY_H4078_serviceErrorString120 &OD->list[177]
#define OD_ENTRY_H4079_serviceErrorString121 &OD->list[178]
#define OD_ENTRY_H407A_serviceErrorString122 &OD->list[179]
#define OD_ENTRY_H407B_serviceErrorString123 &OD->list[180]
#define OD_ENTRY_H407C_serviceErrorString124 &OD->list[181]
#define OD_ENTRY_H407D_serviceErrorString125 &OD->list[182]
#define OD_ENTRY_H407E_serviceErrorString126 &OD->list[183]
#define OD_ENTRY_H407F_serviceErrorString127 &OD->list[184]
#define OD_ENTRY_H6000_digitalInputs &OD->list[185]
#define OD_ENTRY_H6200_digitalInputs &OD->list[186]
#define OD_ENTRY_H6401_analogInputs &OD->list[187]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
